### ISSUE TITLE
Add user guide text

### ISSUE THREAD

**Issue by Abigail770** [USGS-WiM/fim-harrisonville-mo#23]
Wait on text from cooperator

**Comment by HansVraga** [comment]
@njestes did you get good notes on what they wanted there? If so, you could park them here and assign this issue to one of our new students - this and #44 seem like good adds to the Student Issues Board. https://github.com/orgs/USGS-WiM/projects/12 

Alternatively, I can also see just removing this section.

**Comment by njestes** [comment]
@HansVraga They haven't given us anything other than saying they like the one on the FIM mapper. So we could just use what's there, remove things that don't make sense and replace some screenshots. Would be some work/wording to add some of the unique features like 'Dry/Normal/Wet' antecedent conditions and the precip/duration siders in place gage height slider.

I do like the idea of assigning to new WIMmers 👍

**Comment by HansVraga** [comment]
For whoever picks up this task: this application (test url: https://test.wim.usgs.gov/fim-harrisonville-mo/#/ ) is similar to fim ( https://fim.wim.usgs.gov/fim/ ) except it covers only one site and has a couple of extra features (Nick mentions the primary ones, above). Populate a user guide (button in the upper-right of both applications) with applicable content.
